# Generated by Django 6.0.3 on 2026-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolleyPlayer',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('position', models.CharField(choices=[('Setter', 'Setter'), ('Outside Hitter', 'Outside Hitter'), ('Middle Blocker', 'Middle Blocker'), ('Opposite Hitter', 'Opposite Hitter'), ('Libero', 'Libero'), ('Defensive Specialist', 'Defensive Specialist')], max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
